### ISSUE TITLE
changing the name of react to rudra

### ISSUE THREAD

**Issue by ayushnau** [Harshal0902/Rudra#128] opened 2021-07-24 08:04 UTC
In the react version still the name is React App should I chang this to RUDRA

**Comment by Harshal0902** [comment] 2021-07-24 09:55
In public/index.html file?

**Comment by ayushnau** [comment] 2021-07-25 06:55
yes

**Comment by Harshal0902** [comment] 2021-07-25 07:01
@Ayush2020012016 go for it

**Comment by gargkrishna** [comment] 2021-08-05 21:00
I want to contribute to this issue. can you assign me??

**Comment by Harshal0902** [comment] 2021-08-06 05:24
@gargkrishna the issue is assigned to other person, so let wait till tonight, if @Ayush2020012016 didn't do any PR I will assign this issue to you.

**Comment by Harshal0902** [comment] 2021-08-10 10:44
@gargkrishna go for it, try to submit PR till midnight

**Comment by demonking0710** [comment] 2023-04-14 05:55
I want to contribute to this issue.Can you assign me?

**Comment by demonking0710** [comment] 2023-04-16 04:28
its giving 403 when i am pushing.

**Closed as completed** 2023-04-16 08:08 UTC
Labels: good first issue, 🟩 Level1, LGMSOC21
